### ISSUE TITLE
LoadError: ArgumentError: Package Preconditioners does not have IncompleteSelectedInversion in its dependencies

### ISSUE THREAD

**Issue by UserQuestions** [JuliaLinearAlgebra/Preconditioners.jl#1]
I get the following error when trying to `using Preconditioners` on v0.7.0.

```
LoadError: ArgumentError: Package Preconditioners does not have IncompleteSelectedInversion in its dependencies
```
After which it suggests that if I don't have Preconditioners package checked out for development, then I may need to report the issue with Preconditioners.

I'm guessing this may have something to do with Preconditioners relying on IncompleteSelectedInversions, which is not a registered package. I assume it refers to: [this package](https://github.com/ettersi/IncompleteSelectedInversion.jl).

**Comment by mohdibntarek** [comment]
Yes this is true. Preconditioners.jl does not support v1.0 yet for this reason. I tried absorbing IncompleteSelectedInversions.jl into Preconditioners.jl so I can maintain them together but I am still reluctant to release it until I read the other package fully and understand it to be able to properly maintain it. Which preconditioners are you interested in? I can make a branch for you without this dependency to use with Julia v1.0.

**Comment by UserQuestions** [comment]
@mohamed82008, thanks! I didn't have a specific preconditioner in mind. I have little expertise in preconditioning, so my plan was just to try out any preconditioners that were easily available and see which worked best for the form of system of equations that I need to solve many times.  If there are a set of preconditioners in this package that don't actually use functions from `IncompleteSelectedInversion` and it's not too much work, a branch without the dependency would really be appreciated!

**Comment by mohdibntarek** [comment]
Sure, I will do it this weekend.

**Comment by UserQuestions** [comment]
@mohamed82008, thanks! I appreciate it! Out of curiosity, if I clone and install the `IncompleteSelectedInversion` from GitHub will that work without you needing to create a separate branch?

**Comment by mohdibntarek** [comment]
I don't think ISI is compatible with v1.0 but I didn't check for a while so I may be wrong. I have some local changes which need to be cleaned up and pushed to make that branch.

**Comment by mohdibntarek** [comment]
You can do `] add Preconditioners#v1.0fixes` to get the branch that works with Julia v1.0.

**Comment by mohdibntarek** [comment]
You may need to do `] add AlgebraicMultigrid` before that too. Travis seems to complain about this package which had a change in name recently from `AMG`.

**Comment by UserQuestions** [comment]
Thank you! I will pull down the branch once I have access to my Julia system.  This name explains a lot. I was a bit confused because `AMG` was not compatible with v0.7 when I added it recently (lots of issues when calling functions of adjoints, etc.).  This was surprising to me because the commit log on GitHub seemed to show that you had already merged in changes to fix 0.7 issues.  Now that I look more closely, these fixes were also accompanied by a Travis name-change to `AlgebraicMultigrid`, which is why they did not appear in the package `AMG`.  I really appreciate your following up on this. I probably never would have figured that out.

Also, you may want to change the ReadMe on `AlgebraicMultigrid` to use `using AlgebraicMultigrid` rather than `using AMG`. :)

**Comment by UserQuestions** [comment]
@mohamed82008, to follow up on this. It does appear that you have made edits to `AlgebraicMultigrid` that allow compatibility with 0.7 (with some remaining deprecation warnings), however `AlgebraicMultigrid` is not available directly from the package manager. Only `AMG` is. I don't know anything about how the package manager registry works, but I imagine that something small might not have been edited properly such that `AlgebraicMultigrid` never made it to the Julia registered packages list.  To get the most recent version of `AlgebraicMultigrid` I had to fork and pull the nightly.

**Comment by mohdibntarek** [comment]
Yes I haven't tested `AlgebraicMultigrid.jl` on a clean install before. I think something needs to change with METADATA to make it visible to `Pkg`. @ranjanan might know more about this.

**Comment by mohdibntarek** [comment]
Resolved by the new release.
