### ISSUE TITLE
Bug in AMGPreconditioner

### ISSUE THREAD

**Issue by pmartorell** [JuliaLinearAlgebra/Preconditioners.jl#20]
Hi,

since `AlgebraicMultigrid` v0.4.1 the code breaks in the following snipped:

```
using IterativeSolvers
using Preconditioners
using AlgebraicMultigrid

A = poisson(1000)
b = A*ones(1000)
p = AMGPreconditioner{SmoothedAggregation}(A)
cg(A,b,Pl=p)
```

However, the raw preconditioner can still be used from `AlgebraicMultigrid` package:
```
p = aspreconditioner(smoothed_aggregation(A))
```

**Comment by mohdibntarek** [comment]
Thanks for the report. I opened a PR to fix this.
