### ISSUE TITLE
Move package to JuliaLinearAlgebra?

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLinearAlgebra/Preconditioners.jl#27]
@mohamed82008 would you consider moving this to some organization, e.g. [JuliaLinearAlgebra](https://github.com/JuliaLinearAlgebra), to let more people help with maintenance?

**Comment by mohdibntarek** [comment]
I would be open to that as long as I maintain admin rights to the package.

**Comment by mohdibntarek** [comment]
Sorry for not getting back to your PR btw, it kind of dropped off my radar. I will take a look this weekend.

**Comment by fredrikekre** [comment]
I sent you an invite to the org. If you accept I believe you can transfer it.

**Comment by mohdibntarek** [comment]
Done. Now we need to update the general registry I believe.

**Comment by fredrikekre** [comment]
Yea, I can do that (edit: https://github.com/JuliaRegistries/General/pull/67775). I made you an admin of the package too.
